language: php

sudo: false

git:
  depth: 5

matrix:
  include:
  - php: 7.1
  - php: 7.2
  - php: 7.3
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer install --no-interaction

script: vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
  
